stages:
  - build
  - test
  - examples

image: rust:latest

variables:
  CARGO_TERM_COLOR: always

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target
    - cargo-home

before_script:
  - export CARGO_HOME=$CI_PROJECT_DIR/cargo-home
  - rustc --version
  - cargo --version
  # install cargo-examples subcommand so we can run ALL examples
  - cargo install cargo-examples

build:
  stage: build
  script:
    - cargo build --verbose

test:
  stage: test
  script:
    - cargo test --all --verbose

examples:
  stage: examples
  script:
    - cargo examples --manifest-path ./Cargo.toml
